# Banco de dados PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Configuracoes de producao
spring.thymeleaf.cache=true
server.servlet.session.cookie.secure=true

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH

# Logs mais restritos em producao
logging.level.org.thymeleaf=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=WARN
